name: Deploy to EKS

on:
  workflow_dispatch:   # Run manually

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CD repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1   # change if needed

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name EKS-cluster-terraform --region ap-south-1

      - name: Deploy Manifests to EKS
        run: |
          kubectl apply -f Manifest/
          kubectl get svc -n webapps
          kubectl get pods -n webapps